// Quick test of AI narrative generation

const { generateBattleNarrative } = require('./aiNarrativeEngine');

// Mock combat result
const combatResult = {
    result: 'attacker_major_victory',
    intensity: 'decisive',
    combatRatio: 2.5,
    attackerPower: 15,
    defenderPower: 6
};

// Mock battle context
const battleContext = {
    attackerCulture: 'Roman',
    defenderCulture: 'Celtic',
    terrain: 'forest',
    turnNumber: 5,
    formations: {
        attacker: 'testudo',
        defender: 'loose'
    }
};

// Run test
async function test() {
    console.log('🎬 Testing AI Narrative Generation...\n');
    
    const narrative = await generateBattleNarrative(
        combatResult,
        battleContext,
        {}, // No officer memories
        []  // No turn history
    );
    
    console.log('📖 GENERATED NARRATIVE:');
    console.log('='.repeat(60));
    console.log(narrative.mainNarrative.fullNarrative);
    console.log('='.repeat(60));
    console.log('\n✅ Test complete!');
    console.log(`Generated by: ${narrative.mainNarrative.generated_by || 'template'}`);
}

test().catch(console.error);