// src/game/officers/veteranWarnings.js
// AI-generated veteran warnings based on experience

/**
 * Check if veteran officers should warn about risky orders
 * Returns trigger conditions - actual warning generated by AI
 */
function shouldVeteransWarn(orderText, battleState, playerSide, veterans) {
    if (veterans.length === 0) return null;
    
    const triggers = [];
    const intel = battleState[playerSide]?.intelMemory || [];
    const myUnits = battleState[playerSide]?.units || [];
    const enemyCulture = battleState[playerSide === 'player1' ? 'player2' : 'player1']?.culture;
    
    // Trigger 1: Historical enemy knowledge
    if (enemyCulture && hasFacedCultureBefore(veterans, enemyCulture)) {
        triggers.push({
            type: 'historical_knowledge',
            severity: 'medium',
            context: {
                enemyCulture,
                veteranExperience: getMostExperiencedAgainst(veterans, enemyCulture),
                orderText
            }
        });
    }
    
    // Trigger 2: Similar past battle situation
    const similarMemory = findSimilarBattleMemory(veterans, orderText, battleState);
    if (similarMemory) {
        triggers.push({
            type: 'battle_memory',
            severity: 'high',
            context: {
                memory: similarMemory,
                orderText,
                situation: describeCurrentSituation(battleState, playerSide)
            }
        });
    }
    
    // Trigger 3: Morale/insubordination risk
    const moraleRisk = checkMoraleRisk(orderText, myUnits, battleState[playerSide]);
    if (moraleRisk) {
        triggers.push({
            type: 'morale_concern',
            severity: moraleRisk.severity,
            context: {
                issue: moraleRisk.issue,
                orderText,
                unitMorale: battleState[playerSide]?.morale || 100
            }
        });
    }
    
    // Trigger 4: Obvious tactical mistakes
    const tacticalRisk = detectObviousTacticalRisk(orderText, intel, myUnits);
    if (tacticalRisk) {
        triggers.push({
            type: 'tactical_risk',
            severity: tacticalRisk.severity,
            context: tacticalRisk.context
        });
    }
    
    return triggers.length > 0 ? {
        veteran: getMostExperienced(veterans),
        triggers
    } : null;
}

/**
 * Check if veterans have faced this culture before
 */
function hasFacedCultureBefore(veterans, culture) {
    return veterans.some(v => 
        v.memories?.some(m => 
            m.enemyCulture === culture || 
            m.keywords?.includes(culture.toLowerCase())
        )
    );
}

/**
 * Get veteran with most experience against specific culture
 */
function getMostExperiencedAgainst(veterans, culture) {
    const experienced = veterans.filter(v =>
        v.memories?.some(m => m.enemyCulture === culture)
    );
    return experienced.length > 0 
        ? experienced.sort((a, b) => b.battles - a.battles)[0]
        : veterans[0];
}

/**
 * Find similar situation in battle memories
 */
function findSimilarBattleMemory(veterans, orderText, battleState) {
    for (const veteran of veterans) {
        if (!veteran.memories) continue;
        
        for (const memory of veteran.memories) {
            // Check if order text matches memory keywords
            if (memory.keywords?.some(k => 
                new RegExp(k, 'i').test(orderText)
            )) {
                return {
                    veteran,
                    memory,
                    outcome: memory.outcome // 'success' or 'disaster'
                };
            }
        }
    }
    return null;
}

/**
 * Check for morale/insubordination risks
 */
function checkMoraleRisk(orderText, myUnits, playerState) {
    const morale = playerState?.morale || 100;
    
    // Retreat orders with good morale = no problem
    // Retreat orders with low morale = may refuse
    if (/retreat|withdraw|fall back/i.test(orderText) && morale < 30) {
        return {
            severity: 'critical',
            issue: 'retreat_low_morale',
            description: 'Men are already wavering - retreat order may cause rout'
        };
    }
    
    // Suicidal orders = morale concern
    if (/hold to death|last stand|no retreat/i.test(orderText) && morale < 50) {
        return {
            severity: 'high',
            issue: 'suicide_mission',
            description: 'Ordering men to die when morale is shaky - may refuse'
        };
    }
    
    // Aggressive orders with low morale
    if (/charge|attack|assault/i.test(orderText) && morale < 40) {
        return {
            severity: 'medium',
            issue: 'attack_low_morale',
            description: 'Men are fearful - aggressive orders may not be followed'
        };
    }
    
    return null;
}

/**
 * Detect obvious tactical risks
 */
function detectObviousTacticalRisk(orderText, intel, myUnits) {
    // Cavalry threat during advance
    const enemyCavalry = intel.filter(i => /cavalry|horse/i.test(i.unitClass));
    if (enemyCavalry.length > 0 && /advance|charge|attack/i.test(orderText)) {
        return {
            severity: 'high',
            context: {
                risk: 'cavalry_flank',
                cavalryPositions: enemyCavalry.map(c => c.position),
                orderText
            }
        };
    }
    
    // Defended crossing
    if (/cross|ford/i.test(orderText)) {
        const defendedCrossing = intel.filter(i => 
            /11|12/.test(i.position) && /infantry/i.test(i.unitClass)
        );
        if (defendedCrossing.length > 0) {
            return {
                severity: 'high',
                context: {
                    risk: 'defended_crossing',
                    defenderCount: defendedCrossing.length,
                    orderText
                }
            };
        }
    }
    
    return null;
}

/**
 * Describe current tactical situation
 */
function describeCurrentSituation(battleState, playerSide) {
    const intel = battleState[playerSide]?.intelMemory || [];
    const myUnits = battleState[playerSide]?.units || [];
    
    return {
        enemyUnitsDetected: intel.length,
        myUnitCount: myUnits.length,
        morale: battleState[playerSide]?.morale || 100,
        terrain: battleState.terrain || 'unknown'
    };
}

/**
 * Get most experienced veteran
 */
function getMostExperienced(veterans) {
    return veterans.sort((a, b) => b.battles - a.battles)[0];
}

module.exports = {
    shouldVeteransWarn
};